version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: argus-db
    environment:
      POSTGRES_DB: argus_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    container_name: argus-minio
    ports:
      - "9000:9000" # API S3
      - "9001:9001" # Console Web
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"

  # O Redis será útil para o Rate Limit (Requisito Sênior)
  redis:
    image: redis:alpine
    container_name: argus-redis
    ports:
      - "6379:6379"